//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTask
    {
        public int ID { get; set; }
        public int StudentsID { get; set; }
        public int TaskID { get; set; }
        public int Point { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Task Task { get; set; }
    }
}
